# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ezcrypto 0.8.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ezcrypto".freeze
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kendra".freeze]
  s.date = "2018-02-21"
  s.description = "Encryption".freeze
  s.email = "kmulvey@providigm.com".freeze
  s.extra_rdoc_files = [
    "README.rdoc",
    "README_ACTIVE_CRYPTO",
    "README_DIGITAL_SIGNATURES"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "MIT-LICENSE",
    "README.rdoc",
    "README_ACTIVE_CRYPTO",
    "README_DIGITAL_SIGNATURES",
    "VERSION",
    "init.rb",
    "lib/active_crypto.rb",
    "lib/ezcrypto.rb",
    "lib/ezsig.rb",
    "lib/trusted.pem",
    "rakefile",
    "test/active_crypto_test.rb",
    "test/agree2.com.cert",
    "test/association_key_holder_test.rb",
    "test/database.yml",
    "test/digest_test.rb",
    "test/dsakey.pem",
    "test/dsapubkey.pem",
    "test/dsig_test.rb",
    "test/encrypt_test.rb",
    "test/ezcrypto_test.rb",
    "test/key_holder_test.rb",
    "test/protectedsigner.pem",
    "test/sf-class2-root.crt",
    "test/sf_intermediate.crt",
    "test/store/bcdd5959.0",
    "test/test_helper.rb",
    "test/testchild.pem",
    "test/testchild.req",
    "test/testpub.pem",
    "test/testsigner.cert",
    "test/testsigner.pem",
    "test/valicert_class2_root.crt"
  ]
  s.homepage = "http://github.com/GitHubAdmin/ezcrypto".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14".freeze
  s.summary = "Encryption.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.6"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    else
      s.add_dependency(%q<rspec>.freeze, ["~> 3.6"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    end
  else
    s.add_dependency(%q<rspec>.freeze, ["~> 3.6"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
  end
end

